language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "python setup.py build"
# command to run tests
script: python setup.py test
notifications:
  email: false
  irc: 
    channels:
      - "chat.freenode.net##legoktm"
    skip_join: true
    on_success: change
    on_failure: always
